<p style="margin-bottom: 0in">Here are some events that we will be attending and where you can find us throughout the year.</p>
<p style="margin-bottom: 0in">We can be found most weekends at the <a target="_blank" href="http://raleighfleamarket.net/"><u><strong>Raleigh Flea Market</strong></u></a> located within the State Fairgrounds at 1025 Blue Ridge Rd at Hillsborough Street in Raleigh NC 27607.</p>
<p style="margin-bottom: 0in">We’re <a target="_blank" href="map.pdf"><u><strong>located</strong></u></a> near the middle of the outside area of the flea market down the center aisle. You can’t miss our bright red canopy. … and even if you do, just follow the smell of great tasting kettle corn being popped fresh. You’ll be sure to find us that way.</p>

<p style="margin-bottom: 0in">The <a target="_blank" href="http://raleighfleamarket.net/"><u><strong>Raleigh Flea Market</strong></u></a> is open all year round (except during the weeks when the State Fair is on in October) and offers some great buys on all kinds of items from a wide variety of vendors. </p>
<p style="margin-bottom: 0in" align="center"><strong>During our scheduled events, we will have a table at the</strong></p>
<p style="margin-bottom: 0in" align="center"><strong> </strong><strong>Raleigh Flea Market selling fresh popped kettle corn</strong>.</p>
<p style="margin-bottom: 0in" align="center"> </p>
<h2 align="center"><font color="#ff0000" size="4">*****ANNOUNCING OUR NEW RETAIL LOCATIONS*****</font></h2>
<p style="margin-bottom: 0in"><font size="4"><a title="" target="null" href="http://www.wholefoods.com"><strong>WHOLE FOODS</strong></a> </font> in North Raleigh and Charlotte and THE BUTCHER'S MARKET in Raleigh at 5045 Falls of Neuse Rd! You can still find us at the Whole Foods in Cary and <font size="4"><a title="" target="null" href="http://www.thebutchersmarkets.com/"><strong>THE BUTCHER'S MARKET</strong></a> </font>on Kildare Farm Rd near the intersection of Cary Parkway in Cary NC and in Charlotte at 8410 Rea Road.</p>

<p style="margin-bottom: 0in">The Butcher's Market is your Neighborhood Butcher shop that offers prime custom cut meats as well as a host of ready to cook marinated meats, poultry and pork; with a wide variety of gourmet sauces, dips, wines, cheese, pasta, snacks and other groceries. It's the local butcher shop plus a whole lot more.</p>
-----------------------------------------------------------------------------------------</p>
<p style="margin-bottom: 0in">We are also scheduled to be at the following events on these dates.</p>

<p><span></span><a title="" target="_blank" href="http://www.mumfest.com" onclick="window.open(this.getAttribute('href'),'MumFest 2009');return false;"><strong>NC MumFest 2013</strong> </a> in New Bern NC - Saturday (9:30 AM- 6:30 PM) & Sunday  (10:30 AM- 5:00 PM) October 12th & 13th, 2013. Located on the streets and waterfront in downtown historic <a title="" target="_blank" href="http://maps.google.com/maps?q=new+bern+nc&rls=com.microsoft:en-us:IE-SearchBox&oe=UTF-8&sourceid=ie7&rlz=1I7GGIG_en&um=1&ie=UTF-8&split=0&gl=us&ei=IfqJStzHF8bBlAfsvJXpDA&sa=X&oi=geocode_result&ct=title&resnum=1" onclick="window.open(this.getAttribute('href'),'Directions');return false;"><strong>New Bern NC</strong></a>, the birthplace of PepsiCola. There are numerous attractions, shows, music entertainers, amusementents and rides, a trampoline act and even an air show; plus much, much more; click here for a list of some of the <a title="" target="_blank" href="http://www.mumfest.com/attractions.shtml" onclick="window.open(this.getAttribute('href'),'Attractions');return false;"><strong>attractions</strong></a> and <a title="" target="_blank" href="http://www.mumfest.com/entertainment.shtml" onclick="window.open(this.getAttribute('href'),'Entertainment');return false;"><strong>entertainment</strong></a>. Check out the <a title="" target="_blank" href="http://www.mumfest.com/festivalmap.shtml" onclick="window.open(this.getAttribute('href'),'Festival Map');return false;"><strong>Festival M</strong><strong>ap</strong><strong> </strong></a>to locate the different areas of events and shows.</p>

<p><a title="" href="http://www.warwickapplefest.com"><strong>Warwick Applefest</strong></a> 2013 in Warwick NY - Sunday October 6th, 2013 held in beautiful Warwick NY, the apple picking capital of the Hudson Valley. Sample some of the best apple pies, cakes, deserts and fresh picked apples from local orchards. Local crafts, artis and vendors of all types of items line the streets. There are also plenty of games and rides for the kids.</p>
<p style="margin-bottom: 0in">In addition to these events, we also provide on-site accommodations or pre-popped packages of kettle corn for local sporting events, fundraisers, birthday parties, church and business picnics/gatherings, as well as other special events. Please <a href="mailto:info@corkyskettlecorn.com"><u><strong>contact us</strong></u></a> for available dates and requirements so that we can make your event a fun and memorable one.</p>